---
services:
  dashboard-service:
    container_name: svc-dashboard
    image: svenschmidt1502/svc-dashboard:latest
    network_mode: host
    environment:
      - 'KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}' 
      - 'KAFKA_GROUP_ID=${KAFKA_GROUP_ID}' 
      - 'KAFKA_CONSUMER_TOPICS=${KAFKA_CONSUMER_TOPICS}'
      - TZ=Europe/Berlin 
    volumes:
      - src/data.json:src/data.json:rw
    deploy:
      replicas: 1

