---
services:
  perceived-temp-service:
    container_name: svc-dashboard
    image: svenschmidt1502/svc-dashboard:latest
    network_mode: host
    ports:
      - 8501:8501
    environment:
      - 'KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}' 
      - 'KAFKA_GROUP_ID=${KAFKA_GROUP_ID}' 
    deploy:
      replicas: 1
