---
services:
  perceived-temp-service:
    container_name: svc-dashboard
    image: svc-dashboard:latest
    environment:
      - 'KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}' 
      - 'KAFKA_GROUP_ID=${KAFKA_GROUP_ID}' 
    deploy:
      replicas: 1